spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3307/proddb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: prodpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    open-in-view: false
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none


